services:
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=test
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306
  wordpress:
    image: wordpress:latest
    user: 1000:1000
    volumes:
      - wp_data:/var/www/html
      - ./wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=test
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=true
volumes:
  db_data:
  wp_data:
